name: Generate Documentation with Docupocus
description: Analyzes code and generates documentation using AI

inputs:
  ai-api-key:
    description: API key for OpenRouter
    required: false

  ai-backend:
    description: Backend type (openrouter or ollama)
    default: openrouter

  ai-model:
    description: AI model to use
    default: deepseek/deepseek-chat-v3-0324:free

  ai-endpoint:
    description: Endpoint for Ollama backend (e.g., http://localhost:11434)
    required: false

runs:
  using: "composite"
  steps:
    - name: 📄 Generate Documentation
      shell: bash
      run: |
        set -e

        CMD="./docupocus \
          --non-interactive \
          --ai-backend \"${{ inputs.ai-backend }}\" \
          --ai-model \"${{ inputs.ai-model }}\" \
          --output docs \
          --verbose"

        if [[ "${{ inputs.ai-backend }}" == "openrouter" ]]; then
          CMD="$CMD --ai-api-key \"${{ inputs.ai-api-key }}\""
        elif [[ "${{ inputs.ai-backend }}" == "ollama" ]]; then
          CMD="$CMD --ai-endpoint \"${{ inputs.ai-endpoint }}\""
        else
          echo "❌ Unsupported AI backend: ${{ inputs.ai-backend }}"
          exit 1
        fi

        echo "📣 Running command: $CMD"
        eval $CMD

    - name: 📦 Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: docupocus-preview
        path: docs/

    - name: 🚀 Push docs to preview branch
      shell: bash
      run: |
        set -e

        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        PREVIEW_BRANCH="docupocus-preview"
        TEMP_DIR="/tmp/preserved-docs"

        # ✅ STEP 1: Preserve docs outside repo
        if [ -d "docs" ] && [ "$(ls -A docs)" ]; then
          echo "📁 Saving generated docs to $TEMP_DIR"
          mkdir -p "$TEMP_DIR"
          rsync -av docs/ "$TEMP_DIR/"
        else
          echo "❌ 'docs/' folder not found or is empty. Aborting."
          exit 1
        fi

        # ✅ STEP 2: Create orphan branch and wipe repo
        git fetch origin
        git checkout --orphan "$PREVIEW_BRANCH"
        git reset --hard
        rm -rf * .github .gitignore || true

        # ✅ STEP 3: Restore docs from outside temp dir
        mkdir -p docs
        rsync -av "$TEMP_DIR/" docs/

        # ✅ STEP 4: Commit and push
        touch .nojekyll
        git add docs/
        git commit -m "📝 Docupocus preview"
        git push -f origin "$PREVIEW_BRANCH"