name: Generate Documentation with Docupocus
description: Analyzes code and generates documentation using AI

inputs:
  ai-api-key:
    description: API key for OpenRouter
    required: false

  ai-backend:
    description: Backend type (openrouter or ollama)
    default: openrouter

  ai-model:
    description: AI model to use
    default: deepseek/deepseek-chat-v3-0324:free

  ai-endpoint:
    description: Endpoint for Ollama backend (e.g., http://localhost:11434)
    required: false

runs:
  using: "composite"
  steps:
    - name: 📄 Generate Documentation
      shell: bash
      run: |
        set -e

        CMD="./docupocus \
          --non-interactive \
          --ai-backend \"${{ inputs.ai-backend }}\" \
          --ai-model \"${{ inputs.ai-model }}\" \
          --output docs \
          --verbose"

        if [[ "${{ inputs.ai-backend }}" == "openrouter" ]]; then
          CMD="$CMD --ai-api-key \"${{ inputs.ai-api-key }}\""
        elif [[ "${{ inputs.ai-backend }}" == "ollama" ]]; then
          CMD="$CMD --ai-endpoint \"${{ inputs.ai-endpoint }}\""
        else
          echo "❌ Unsupported AI backend: ${{ inputs.ai-backend }}"
          exit 1
        fi

        echo "📣 Running command: $CMD"
        eval $CMD

    - name: 📦 Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: docupocus-preview
        path: docs/

    - name: 🚀 Push docs to preview branch
      shell: bash
      run: |
        set -e

        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        PREVIEW_BRANCH="docupocus-preview"

        # Save generated docs before switching branches
        mkdir temp-docs
        cp -r docs/* temp-docs/

        # Create new orphan branch
        git fetch origin
        git checkout --orphan $PREVIEW_BRANCH
        git reset --hard
        rm -rf * .github .gitignore || true

        # Restore docs into new branch
        mkdir -p docs
        cp -r temp-docs/* docs/
        rm -rf temp-docs

        touch .nojekyll  # Allow GitHub Pages to serve files from /docs

        git add docs/
        git commit -m "📝 Docupocus preview"
        git push -f origin $PREVIEW_BRANCH
