name: Generate Docs

on:
  # pull_request:
  #   types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write  # Required to push branches

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: 🔨 Build Docupocus
        run: go build -o docupocus ./cmd/docupocus/

      - name: 📄 Generate Docs with Docupocus Action
        uses: ./.github/actions/docupocus
        with:
          ai-api-key: ${{ secrets.OPENROUTER_API_KEY }}
          ai-backend: openrouter
          ai-model: deepseek/deepseek-chat-v3-0324:free
          pr-number: ${{ github.event.pull_request.number }}
